#!/usr/bin/env python3
"""
AGSG CCF FE Scraper
===================
Downloads boxart, video snaps and gamelist.xml from ScreenScraper.fr
for use with the Atari Gamestation Go custom frontend (AGSG CCF FE).

Requirements:
    pip install requests

Usage:
    python3 scraper.py --games-dir /media/user/SDCARD/Games --user Kefren68

ScreenScraper account: https://www.screenscraper.fr/membreinscription.php
Note: use your USERNAME (not email) in --user
"""

import os
import re
import sys
import json
import time
import hashlib
import struct
import zlib
import zipfile
import argparse
import tempfile
import shutil
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

SCRAPER_VERSION = "1.7.1"

# ROM extension whitelist from ScreenScraper (generated by screenscraper_extensions.py)
try:
    from screenscraper_extensions import SYSTEM_EXTENSIONS
except ImportError:
    SYSTEM_EXTENSIONS = {}
import xml.etree.ElementTree as ET
import xml.dom.minidom
from pathlib import Path
from getpass import getpass
from urllib.parse import urlparse, urlunparse, parse_qs, urlencode

# Authentication parameters that ScreenScraper embeds in media URLs.
# These must be stripped before caching URLs to disk.
_AUTH_PARAMS = frozenset({"devid", "devpassword", "ssid", "sspassword", "softname"})

def _strip_auth_params(url):
    """Return url with ScreenScraper authentication query parameters removed."""
    parsed = urlparse(url)
    clean  = {k: v[0] for k, v in parse_qs(parsed.query, keep_blank_values=True).items()
              if k not in _AUTH_PARAMS}
    return urlunparse(parsed._replace(query=urlencode(clean)))


# ---------------------------------------------------------------------------
# ROM filename cleaner: strips region/revision tags for fallback searches
# e.g. "Super Mario World (USA) (Rev 1) [!].sfc" → "Super Mario World"
# WHDLoad Amiga format: "FirstSamurai_v2.1_1182.lha" → "FirstSamurai"
# ---------------------------------------------------------------------------
_TAG_RE      = re.compile(r'[\(\[][^\)\]]*[\)\]]')
_WHDLOAD_RE  = re.compile(r'_v\d.*$|_\d{3,}.*$', re.IGNORECASE)  # _v2.1_1182 etc.
_UNDERSCORE_RE = re.compile(r'[_]+')

# Region detection from ROM filename tags (No-Intro / GoodSet / TOSEC conventions)
# Matches the content of the FIRST (…) or […] tag that is a known region code.
_FILENAME_REGION_RE = re.compile(
    r'[\(\[](USA|Europe|Japan|World|EUR|JPN|JAP|U|E|J|W)[\)\]]',
    re.IGNORECASE
)
_FILENAME_REGION_MAP = {
    'usa': 'us',    'u': 'us',
    'europe': 'eu', 'eur': 'eu', 'e': 'eu',
    'japan': 'jp',  'jpn': 'jp', 'jap': 'jp', 'j': 'jp',
    'world': 'wor', 'w': 'wor',
}

def _detect_region_from_filename(stem):
    """Return a ScreenScraper region code inferred from ROM filename tags, or None."""
    m = _FILENAME_REGION_RE.search(stem)
    if m:
        return _FILENAME_REGION_MAP.get(m.group(1).lower())
    return None

def strip_rom_tags(filename):
    """Return filename with all (…) and […] tags removed, trimmed."""
    stem = Path(filename).stem
    cleaned = _TAG_RE.sub('', stem).strip(' .-_')
    ext = Path(filename).suffix
    return (cleaned + ext) if cleaned else filename

def fallback_names(filename):
    """
    Generate a sequence of progressively simpler names to try on ScreenScraper.
    Yields names that differ from the original (skip duplicates).
    """
    ext  = Path(filename).suffix
    stem = Path(filename).stem
    seen = {filename.lower()}

    def _try(name):
        n = name.strip(' .-_')
        candidate = (n + ext) if n else None
        if candidate and candidate.lower() not in seen:
            seen.add(candidate.lower())
            return candidate
        return None

    # Step 1: strip (…) and […] tags
    s1 = _TAG_RE.sub('', stem)
    if (c := _try(s1)):
        yield c
        stem = s1.strip(' .-_')   # use as base for further steps

    # Step 2: strip WHDLoad-style _vX.Y_NNNN suffixes
    s2 = _WHDLOAD_RE.sub('', stem)
    if (c := _try(s2)):
        yield c
        stem = s2.strip(' .-_')

    # Step 3: progressively strip trailing _word segments (e.g. gamename_publisher_disk1)
    parts = stem.split('_')
    while len(parts) > 1:
        parts.pop()
        s_strip = '_'.join(parts)
        if (c := _try(s_strip)):
            yield c
            # also try with spaces
            s_strip_sp = _UNDERSCORE_RE.sub(' ', s_strip)
            if (c2 := _try(s_strip_sp)):
                yield c2

    # Step 4: replace remaining underscores with spaces
    s4 = _UNDERSCORE_RE.sub(' ', stem)
    if (c := _try(s4)):
        yield c

# ---------------------------------------------------------------------------
# ScreenScraper system ID mapping
# Keys must match (lowercased + stripped) folder names in Games/
# ---------------------------------------------------------------------------
SYSTEM_IDS = {
    "amiga":                64,
    "amstrad cpc":          65,
    "atari 800":            43,
    "atari 2600":           26,
    "atari 2600 paddle":    26,
    "atari 2600 homebrew":  26,
    "atari 5200":           40,
    "atari 7800":           41,
    "atari lynx":           28,
    "atari st":             42,
    "colecovision":         48,
    "commodore 64":         66,
    "game and watch":       52,
    "gameboy":              9,
    "gameboy advance":      12,
    "gameboy color":        10,
    "intellivision":        115,
    "intellivision homebrew":        115,
    "cps1":                 6,
    "cps2":                 7,
    "cps3":                 8,
    "mame":                 75,
    "microvision":          138,
    "msx":                  113,
    "MSDOS":                135,
    "neo geo":              142,
    "neo geo pocket color": 25,
    "nes":                  3,
    "odyssey2":             104,
    "pc engine":            31,
    "pc engine cd":         114,
    "playstation":          57,
    "scummvm":              123,
    "sega 32x":             19,
    "sega cd":              20,
    "sega game gear":       21,
    "sega genesis":         1,
    "sega master system":   2,
    "sg 1000":              109,
    "sg-1000":              109,
    "sharp x1":             220,
    "snes":                 4,
    "ti99sim":              205,
    "TRS-80":               144,
    "cassette vision":      300,
    "epoch cassette vision": 300,
    "cannonball":           13,
    "cave story":           13,
    "doom":                 13,
    "xrick":                13,
    "vectrex":              102,
    "virtualboy":           11,
    "wonderswan color":     46,
    "zx spectrum":          76,
}

API_BASE        = "https://www.screenscraper.fr/api2"

# ---------------------------------------------------------------------------
# Dynamic system map fetched from ScreenScraper API (cached after first call)
# ---------------------------------------------------------------------------
_dynamic_system_ids_cache = None  # type: dict | None

def build_screenscraper_system_ids(devid=None, devpassword=None):
    """
    Fetch the complete system list from ScreenScraper (245+ systems) and
    return a name → system_id mapping built from all available name fields.
    Result is cached globally so the API is called only once per session.
    Falls back to empty dict on network failure; caller merges with SYSTEM_IDS.
    """
    global _dynamic_system_ids_cache
    if _dynamic_system_ids_cache is not None:
        return _dynamic_system_ids_cache

    _devid  = devid  or DEFAULT_DEVID
    _devpw  = devpassword or DEFAULT_DEVPASSWORD

    print("Fetching system list from ScreenScraper...", end=" ", flush=True)
    try:
        params = {
            "devid":       _devid,
            "devpassword": _devpw,
            "softname":    SOFT_NAME,
            "output":      "json",
        }
        r = requests.get(f"{API_BASE}/systemesListe.php",
                         params=params, timeout=REQUEST_TIMEOUT, verify=False)
        r.raise_for_status()
        systems = r.json().get("response", {}).get("systemes", [])
    except Exception as e:
        print(f"failed ({e}). Using built-in list only.")
        _dynamic_system_ids_cache = {}
        return {}

    mapping = {}
    for s in systems:
        try:
            sid = int(s.get("id", 0))
        except (ValueError, TypeError):
            continue
        if not sid:
            continue
        noms = s.get("noms", {})
        for field in ("nom_eu", "nom_us", "nom_jp", "nom_recalbox",
                      "nom_retropie", "nom_launchbox", "nom_hyperspin", "noms_commun"):
            for part in noms.get(field, "").split(","):
                part = part.strip().lower()
                if part and part not in mapping:
                    mapping[part] = sid

    print(f"{len(systems)} systems loaded ({len(mapping)} name aliases).")
    _dynamic_system_ids_cache = mapping
    return mapping
SOFT_NAME       = "skyscraper"
REQUEST_TIMEOUT = 30
DEFAULT_DELAY   = 1.5   # seconds between requests (free account: 1 thread)
MAX_MD5_SIZE    = 256 * 1024 * 1024  # skip MD5 for ROMs larger than 256 MB

# Public developer credentials (from open-source Skyscraper project, MIT-compatible use)
DEFAULT_DEVID       = "muldjord"
DEFAULT_DEVPASSWORD = "uWu5VRc9QDVMPpD8"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def md5_of_file(path):
    """Return MD5 hex digest of a file."""
    h = hashlib.md5()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

# Systems where the ZIP file itself is the ROM artifact that ScreenScraper indexes.
# For these, we hash the whole ZIP (MD5 + CRC32 of the ZIP file), not the inner content.
# Arcade systems: the ZIP *is* the game set (chip files inside are not individually indexed).
# European computer systems: No-Intro / SS distributes and indexes the ZIP directly.
_ZIP_AS_ROM_SYSTEM_IDS = frozenset([
    6, 7, 8,    # CPS1, CPS2, CPS3
    75,         # MAME
    142,        # Neo Geo
    113,        # MSX
    116,        # MSX2
    117,        # MSX2+
    118,        # MSX Turbo R
    64,         # Amiga
    65,         # Amstrad CPC
    66,         # Commodore 64
    42,         # Atari ST
    76,         # ZX Spectrum
])

# Arcade systems where rcheevos (FBNeo core) uses rc_hash_arcade() to hash
# the ROM *filename* (without extension) as an ASCII string — NOT the file
# content.  e.g.  sf2.zip  →  MD5("sf2").
# NOTE: MAME (system 75) is intentionally NOT listed — RA does not support MAME.
#       Only FBNeo-backed systems are listed here.
_RA_ARCADE_SYSTEM_IDS = frozenset([
    6, 7, 8,    # CPS1, CPS2, CPS3  (via FBNeo)
    142,        # Neo Geo            (via FBNeo)
])

# Mapping: ScreenScraper system ID → RetroAchievements console ID.
# RA's dorequest.php?r=gameid endpoint accepts c=CONSOLE_ID to restrict the
# hash search to a specific console's database.  Without this, the global
# search may miss games in the Arcade section (FBNeo, console 27), because
# CPS1/2/3 and Neo Geo are registered under RA's Arcade console, not under
# separate per-system consoles as ScreenScraper has them.
_SS_TO_RA_CONSOLE_ID = {
    6:   27,   # CPS1   → RA Arcade (FBNeo, console 27)
    7:   27,   # CPS2   → RA Arcade (FBNeo, console 27)
    8:   27,   # CPS3   → RA Arcade (FBNeo, console 27)
    142: 27,   # Neo Geo → RA Arcade (FBNeo, console 27)
}

def crc32_of_file(path):
    """Return CRC32 as 8-char uppercase hex string (ScreenScraper romcrc format)."""
    crc = 0
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            crc = zlib.crc32(chunk, crc)
    return f"{crc & 0xFFFFFFFF:08X}"

def _md5_of_file(path):
    """Return MD5 hex digest of a whole file (used for arcade ZIPs)."""
    h = hashlib.md5()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

# Disc/tape image formats that rcheevos hashes by reading specific CD sectors —
# too complex to reproduce here.  These fall back to ScreenScraper's field.
# NOTE: .bin and .img are intentionally NOT listed — they are also used as plain
# cartridge ROM dumps (Atari 2600, ColecoVision, etc.).  When .bin is a CD
# track it always accompanies a .cue file, which IS listed here.
_RA_CD_FORMATS = frozenset([
    ".cue", ".gdi", ".cdi",   # disc descriptor files (PS1, Saturn, Dreamcast)
    ".chd",                    # compressed disc image (multi-system)
    ".pbp",                    # PSP/PS1 package
    ".m3u",                    # multi-disc playlist
    ".ccd", ".sub",            # CloneCD descriptor / subchannel
    ".iso",                    # generic ISO (PS2, PSP, 3DO, …)
])


def _ra_rom_md5(rom_path, system_id=None):
    """Compute the rcheevos-compatible MD5 hash used by RetroAchievements.

    RetroArch uses rcheevos (rc_hash.c) which applies system-specific
    pre-processing before computing MD5.  A plain file MD5 only matches for
    systems that need no pre-processing; for others the hash won't be found in
    the RA database even though the game has achievements.

    Pass system_id (ScreenScraper system ID) so that arcade systems (Neo Geo,
    CPS1/2/3) are hashed as MD5 of the filename stem, matching what rcheevos
    does via rc_hash_arcade() for the FBNeo core.

    Returns None for disc-image formats and on any error — the caller then
    falls back to ScreenScraper's retroachievement field.

    Pre-processing rules (from rcheevos rc_hash.c):
    ┌──────────────────────────────┬─────────────────────────────────────────────┐
    │ System / extension           │ Rule                                        │
    ├──────────────────────────────┼─────────────────────────────────────────────┤
    │ NES          (.nes)          │ Strip 16-byte iNES header if magic NES\\x1a │
    │ SNES         (.sfc/.smc/.fig)│ Strip 512-byte copier header if             │
    │                              │   filesize % 1024 == 512                    │
    │ PC Engine    (.pce/.sgx)     │ Same 512-byte rule as SNES                  │
    │ Atari 7800   (.a78)          │ Strip 128-byte A78 header                   │
    │                              │   (byte 0 == 0x01, bytes 1-9 == "ATARI7800")│
    │ Atari Lynx   (.lnx)          │ Strip 64-byte LNX header (magic b"LYNX")    │
    │ N64          (.v64)          │ Word-swap all bytes (→ big-endian)          │
    │ N64          (.n64)          │ 4-byte group reverse (→ big-endian)         │
    │ NDS          (.nds)          │ MD5(header[0:0x160] + ARM9 binary)          │
    │ Sega MD      (.smd)          │ Skip 512-byte header, deinterleave 16KB blks│
    │ Everything else              │ Plain MD5 of (decompressed) content         │
    │   (GB/GBC/GBA, MD .md/.gen,  │                                             │
    │    SMS/GG, A2600/5200, CV,   │                                             │
    │    Intv, NGP, WS, VB, …)    │                                             │
    └──────────────────────────────┴─────────────────────────────────────────────┘
    """
    suffix = rom_path.suffix.lower()
    try:
        if suffix == ".zip":
            # Arcade systems (CPS1/2/3, Neo Geo): rcheevos rc_hash_arcade()
            # hashes the ROM *filename* (without extension) as a byte string —
            # NOT the ZIP contents and NOT the whole file.
            # e.g.  sf2.zip  →  MD5("sf2")
            # Source: rcheevos/src/rhash/hash.c  rc_hash_arcade()
            if system_id in _RA_ARCADE_SYSTEM_IDS:
                stem = rom_path.stem  # filename without .zip
                return hashlib.md5(stem.encode("ascii", errors="replace")).hexdigest()
            with zipfile.ZipFile(rom_path, "r") as zf:
                members = [m for m in zf.infolist() if not m.is_dir()]
                if not members:
                    return None
                entry = max(members, key=lambda m: m.file_size)
                inner_suffix = Path(entry.filename).suffix.lower()
                if inner_suffix in _RA_CD_FORMATS:
                    return None  # disc image inside zip — can't hash correctly
                with zf.open(entry) as f:
                    data = f.read()
        else:
            if suffix in _RA_CD_FORMATS:
                return None  # disc image — fall back to ScreenScraper field
            inner_suffix = suffix
            with open(rom_path, "rb") as f:
                data = f.read()
    except Exception:
        return None

    # ------------------------------------------------------------------
    # rcheevos-compatible pre-processing (rc_hash.c)
    # ------------------------------------------------------------------

    if inner_suffix == ".nes":
        # iNES / NES 2.0 header: 16 bytes starting with "NES\x1a"
        if data[:4] == b"NES\x1a" and len(data) > 16:
            data = data[16:]

    elif inner_suffix in (".sfc", ".smc", ".fig"):
        # SNES: 512-byte copier header present when filesize % 1024 == 512
        if len(data) % 1024 == 512:
            data = data[512:]

    elif inner_suffix in (".pce", ".sgx"):
        # PC Engine / SuperGrafx: same 512-byte copier header rule as SNES
        if len(data) % 1024 == 512:
            data = data[512:]

    elif inner_suffix == ".a78":
        # Atari 7800: 128-byte A78 header → byte 0 == 0x01, bytes 1-9 == "ATARI7800"
        if len(data) > 128 and data[0:1] == b"\x01" and data[1:10] == b"ATARI7800":
            data = data[128:]

    elif inner_suffix == ".lnx":
        # Atari Lynx: 64-byte LNX header starting with "LYNX"
        if len(data) > 64 and data[:4] == b"LYNX":
            data = data[64:]

    elif inner_suffix == ".v64":
        # N64 word-swapped (V64 / Doctor V64): swap every pair of bytes → big-endian
        arr = bytearray(data)
        arr[0::2], arr[1::2] = bytearray(arr[1::2]), bytearray(arr[0::2])
        data = bytes(arr)

    elif inner_suffix == ".n64":
        # N64 little-endian (N64 / Mr. Backup Z64): reverse each 4-byte group → big-endian
        arr = bytearray(data)
        for i in range(0, len(arr) - 3, 4):
            arr[i], arr[i+1], arr[i+2], arr[i+3] = arr[i+3], arr[i+2], arr[i+1], arr[i]
        data = bytes(arr)

    elif inner_suffix == ".nds":
        # Nintendo DS: MD5 of ROM header (0x160 bytes) + ARM9 binary.
        # ARM9 ROM offset at bytes 0x20-0x23, ARM9 size at 0x2C-0x2F (little-endian).
        if len(data) < 0x160:
            return None
        arm9_offset = struct.unpack_from("<I", data, 0x20)[0]
        arm9_size   = struct.unpack_from("<I", data, 0x2C)[0]
        header = data[:0x160]
        arm9_end = arm9_offset + arm9_size
        arm9 = data[arm9_offset:arm9_end] if (arm9_size > 0 and arm9_end <= len(data)) else b""
        return hashlib.md5(header + arm9).hexdigest()

    elif inner_suffix == ".smd":
        # Sega Mega Drive interleaved dump (Super Magic Drive format).
        # 512-byte SMD header is skipped, then ROM data is stored in 16 KB blocks
        # where odd ROM bytes occupy the first 8 KB and even ROM bytes the second 8 KB.
        if len(data) <= 512:
            return None
        rom = data[512:]        # skip 512-byte SMD header
        out = bytearray()
        HALF = 0x2000           # 8 KB
        BLOCK = HALF * 2        # 16 KB
        for blk_start in range(0, len(rom), BLOCK):
            block = rom[blk_start:blk_start + BLOCK]
            half  = len(block) // 2
            for i in range(half):
                out.append(block[half + i])  # even ROM byte (low)
                out.append(block[i])          # odd  ROM byte (high)
        data = bytes(out)

    # All other systems use plain MD5:
    #   Game Boy / GBC / GBA, Sega MD (.md/.gen), Master System, Game Gear,
    #   Atari 2600/5200 (.bin/.a26/.a52), ColecoVision, Intellivision,
    #   Neo Geo Pocket, WonderSwan, Virtual Boy, Vectrex, SG-1000, 32X,
    #   MSX ROMs, Arduboy, Magnavox Odyssey 2, Fairchild Channel F, …
    return hashlib.md5(data).hexdigest()


def _rom_hashes(rom_path):
    """Return (crc32_hex, md5_hex, inner_name, size) for a ROM file.

    For .zip archives, hashes and name refer to the largest file inside
    (the actual ROM), since ScreenScraper indexes the uncompressed content.
    For plain files, hashes are computed directly on the file.
    """
    suffix = rom_path.suffix.lower()
    if suffix == ".zip":
        try:
            with zipfile.ZipFile(rom_path, "r") as zf:
                # Pick the largest member (most likely the ROM, not a readme/nfo)
                members = [m for m in zf.infolist() if not m.is_dir()]
                if not members:
                    raise ValueError("empty zip")
                entry = max(members, key=lambda m: m.file_size)
                # CRC32 is stored uncompressed in the zip central directory
                crc_hex = f"{entry.CRC & 0xFFFFFFFF:08X}"
                # MD5 requires reading the decompressed content
                h = hashlib.md5()
                with zf.open(entry) as f:
                    while True:
                        chunk = f.read(65536)
                        if not chunk:
                            break
                        h.update(chunk)
                return crc_hex, h.hexdigest(), entry.filename, entry.file_size
        except Exception:
            pass  # fall through to plain-file hashing
    # Plain file (or failed zip)
    h = hashlib.md5()
    crc = 0
    size = rom_path.stat().st_size
    with open(rom_path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
            crc = zlib.crc32(chunk, crc)
    return f"{crc & 0xFFFFFFFF:08X}", h.hexdigest(), rom_path.name, size


def pick_region(items, tag_key, preferred, text_key="text", fallback=None):
    """
    Pick the best value from a list of region/language-tagged dicts.
    Tries preferred → fallback → 'wor' → first available.
    """
    # ScreenScraper's PHP API sometimes returns a single item as a dict instead of a list
    if isinstance(items, dict):
        items = [items]
    if not items:
        return None
    for item in items:
        if item.get(tag_key, "").lower() == preferred.lower():
            return item.get(text_key)
    if fallback and fallback.lower() != preferred.lower():
        for item in items:
            if item.get(tag_key, "").lower() == fallback.lower():
                return item.get(text_key)
    for item in items:
        if item.get(tag_key, "").lower() == "wor":
            return item.get(text_key)
    return items[0].get(text_key)


# ---------------------------------------------------------------------------
# Optional SFTP support  (requires: pip install paramiko)
# ---------------------------------------------------------------------------

class SFTPContext:
    """
    Thin wrapper around paramiko SFTP for reading ROM lists from a remote
    device and writing scraper outputs (boxart, videos, gamelist.xml …) back.
    """

    def __init__(self, host, port, username, password=None, key_filename=None,
                 passphrase=None):
        import paramiko  # type: ignore  (optional dependency)

        # Expand ~ in an explicit key path
        if key_filename:
            key_filename = os.path.expanduser(key_filename)

        # If no key given, consult ~/.ssh/config (like the ssh CLI does)
        if not key_filename:
            try:
                _cfg = paramiko.SSHConfig()
                _cfg_path = os.path.expanduser("~/.ssh/config")
                if os.path.exists(_cfg_path):
                    with open(_cfg_path) as _f:
                        _cfg.parse(_f)
                _h = _cfg.lookup(host)
                if _h.get("identityfile"):
                    key_filename = os.path.expanduser(_h["identityfile"][0])
            except Exception:
                pass

        self._client = paramiko.SSHClient()
        self._client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        self._client.connect(
            host, port=int(port), username=username,
            password=password or None,
            key_filename=key_filename or None,
            passphrase=passphrase or None,
            timeout=15,
        )
        self._sftp = self._client.open_sftp()

    def close(self):
        try:
            self._sftp.close()
            self._client.close()
        except Exception:
            pass

    def exists(self, remote_path):
        try:
            self._sftp.stat(remote_path)
            return True
        except FileNotFoundError:
            return False

    def makedirs(self, remote_path):
        """Recursive mkdir for a remote path (like mkdir -p)."""
        import posixpath
        parts = remote_path.replace("\\", "/").split("/")
        current = ""
        for part in parts:
            if not part:
                current = "/"
                continue
            current = current.rstrip("/") + "/" + part
            try:
                self._sftp.stat(current)
            except FileNotFoundError:
                try:
                    self._sftp.mkdir(current)
                except OSError:
                    pass  # may already exist

    def put(self, local_path, remote_path):
        """Upload a local file to the remote path."""
        self.makedirs(str(Path(remote_path).parent).replace("\\", "/"))
        self._sftp.put(str(local_path), remote_path)

    def get(self, remote_path, local_path):
        """Download a remote file to a local path."""
        Path(local_path).parent.mkdir(parents=True, exist_ok=True)
        self._sftp.get(remote_path, str(local_path))

    def list_subdirs(self, remote_path):
        """Return names of immediate non-hidden subdirectories."""
        import stat as _st
        try:
            attrs = self._sftp.listdir_attr(remote_path)
        except FileNotFoundError:
            return []
        return [a.filename for a in attrs
                if _st.S_ISDIR(a.st_mode or 0) and not a.filename.startswith(".")]

    def list_files_recursive(self, remote_path):
        """
        Return list of (remote_file_path, size, filename) for all files
        under remote_path, recursively.
        """
        import stat as _st
        results = []
        try:
            attrs = self._sftp.listdir_attr(remote_path)
        except FileNotFoundError:
            return []
        for a in attrs:
            full = remote_path.rstrip("/") + "/" + a.filename
            if _st.S_ISDIR(a.st_mode or 0):
                if not a.filename.startswith("."):
                    results.extend(self.list_files_recursive(full))
            else:
                results.append((full, a.st_size or 0, a.filename))
        return results

    def list_files_in_dir(self, remote_path):
        """Return list of filenames (non-recursive) in a remote directory."""
        import stat as _st
        try:
            attrs = self._sftp.listdir_attr(remote_path)
        except FileNotFoundError:
            return []
        return [a.filename for a in attrs if not _st.S_ISDIR(a.st_mode or 0)]


# ---------------------------------------------------------------------------
# ScreenScraper API client
# ---------------------------------------------------------------------------

class ScreenScraperClient:
    def __init__(self, user, password, devid=None, devpassword=None,
                 region="eu", lang="en", delay=DEFAULT_DELAY, verbose=False):
        self.user        = user
        self.password    = password
        self.devid       = devid or DEFAULT_DEVID
        self.devpassword = devpassword or DEFAULT_DEVPASSWORD
        self.region      = region
        self.lang        = lang
        self.delay       = delay
        self.verbose     = verbose
        self._last_call  = 0.0
        self.session     = requests.Session()
        self.session.verify = False
        self.session.headers.update({"User-Agent": f"{SOFT_NAME}/1.0"})
        # Quota tracking (populated from API responses)
        self.requests_today   = None   # type: int | None
        self.max_requests_day = None   # type: int | None
        self.ko_today         = None   # type: int | None  (ROM not found = KO)
        self.max_ko_day       = None   # type: int | None
        # Set to True when a 431 is received: blocks all further API calls
        self.quota_exceeded   = False
        # optional callback(today, max_day, ko_today, max_ko_day)
        self.on_quota_update  = None

    def _throttle(self):
        elapsed = time.time() - self._last_call
        if elapsed < self.delay:
            time.sleep(self.delay - elapsed)
        self._last_call = time.time()

    def _parse_quota(self, data):
        """Extract and store quota info from an API response's ssuser block."""
        ssuser = data.get("response", {}).get("ssuser", {})
        if not ssuser:
            return
        try:
            today      = int(ssuser.get("requeststoday")    or 0)
            max_day    = int(ssuser.get("maxrequestsperday") or 0)
            ko_today   = int(ssuser.get("koscrapestoday")    or 0)
            max_ko_day = int(ssuser.get("maxkoscrapesperday") or 0)
        except (ValueError, TypeError):
            return
        if max_day > 0:
            self.requests_today   = today
            self.max_requests_day = max_day
        if max_ko_day > 0:
            self.ko_today   = ko_today
            self.max_ko_day = max_ko_day
        if self.on_quota_update and (max_day > 0 or max_ko_day > 0):
            self.on_quota_update(
                self.requests_today, self.max_requests_day,
                self.ko_today, self.max_ko_day,
            )

    def quota_str(self):
        """Return a human-readable quota string, or empty string if unknown."""
        parts = []
        if self.requests_today is not None and self.max_requests_day:
            rem = self.max_requests_day - self.requests_today
            parts.append(
                f"Scrape: {self.requests_today}/{self.max_requests_day} ({rem} left)"
            )
        if self.ko_today is not None and self.max_ko_day:
            rem_ko = self.max_ko_day - self.ko_today
            parts.append(
                f"KO: {self.ko_today}/{self.max_ko_day} ({rem_ko} left)"
            )
        return "  |  ".join(parts) if parts else ""

    def _base_params(self):
        p = {
            "devid":      self.devid,
            "devpassword": self.devpassword,
            "softname":   SOFT_NAME,
            "output":     "json",
            "ssid":       self.user,
            "sspassword": self.password,
        }
        return p

    def get_user_quota(self):
        """
        Call ssUserInfos.php to retrieve the current quota before scraping starts.
        Populates self.requests_today / self.max_requests_day and fires the callback.
        Returns True on success, False on network failure.
        """
        try:
            r = self.session.get(
                f"{API_BASE}/ssUserInfos.php",
                params=self._base_params(),
                timeout=REQUEST_TIMEOUT,
            )
            r.raise_for_status()
            self._parse_quota(r.json())
            return True
        except requests.HTTPError as e:
            code = e.response.status_code if e.response is not None else 0
            if code == 431:
                self._parse_quota_from_error(e.response)
            return False
        except Exception:
            return False

    def _parse_quota_from_error(self, response):
        """Try to extract ssuser quota info from a non-200 response body."""
        try:
            data = response.json()
            self._parse_quota(data)
        except Exception:
            pass

    def get_game_info(self, system_id, rom_name, rom_path=None, file_size=None):
        """
        Query ScreenScraper for a single ROM. Returns the 'jeu' dict or None.
        Sends MD5 hash when available for more accurate matching.
        If not found, retries with progressively simplified filenames.
        file_size: pre-computed remote file size (SFTP mode); skips local hash.
        """
        if self.quota_exceeded:
            return None

        jeu = self._query_game_info(system_id, rom_name, rom_path, file_size=file_size)
        if jeu is not None:
            return jeu

        # Progressive fallback: strip tags, WHDLoad suffixes, underscores
        for candidate in fallback_names(rom_name):
            if self.quota_exceeded:
                return None
            if self.verbose:
                print(f"\n      [verbose] not found, retrying as '{candidate}'",
                      file=sys.stderr)
            jeu = self._query_game_info(system_id, candidate, rom_path=None)
            if jeu is not None:
                if self.verbose:
                    print(f"      [verbose] found via '{candidate}'", file=sys.stderr)
                return jeu
        return None

    def _query_game_info(self, system_id, rom_name, rom_path=None, file_size=None):
        """Single API call to jeuInfos.php. Returns 'jeu' dict or None."""
        if self.quota_exceeded:
            return None
        self._throttle()
        params = self._base_params()
        params["systemeid"] = system_id
        params["romnom"]    = rom_name

        if file_size is not None:
            # SFTP mode: we know the size but can't compute hashes locally
            params["romtaille"] = file_size
        elif rom_path and rom_path.exists():
            if rom_path.stat().st_size < MAX_MD5_SIZE:
                try:
                    if rom_path.suffix.lower() == ".zip" and system_id in _ZIP_AS_ROM_SYSTEM_IDS:
                        # Arcade ZIPs (MAME, CPS, Neo Geo): SS indexes the MD5/CRC of the
                        # whole ZIP file, not individual chips. romnom stays as "1942.zip".
                        params["romcrc"]    = crc32_of_file(rom_path)
                        params["rommd5"]    = _md5_of_file(rom_path)
                        params["romtaille"] = rom_path.stat().st_size
                    else:
                        # Non-arcade: hash the inner ROM file (SS indexes uncompressed content).
                        # For ZIPs also override romnom with the inner filename.
                        crc_hex, md5_hex, inner_name, inner_size = _rom_hashes(rom_path)
                        params["romcrc"]    = crc_hex
                        params["rommd5"]    = md5_hex
                        params["romtaille"] = inner_size
                        if rom_path.suffix.lower() == ".zip":
                            params["romnom"] = inner_name
                except OSError:
                    pass
            else:
                params["romtaille"] = rom_path.stat().st_size

        if self.verbose:
            md5_str = params.get("rommd5", "(none)")
            crc_str = params.get("romcrc", "(none)")
            print(f"\n      [verbose] GET jeuInfos  system={system_id}  rom='{rom_name}'  crc={crc_str}  md5={md5_str}",
                  file=sys.stderr)
        try:
            r = self.session.get(f"{API_BASE}/jeuInfos.php",
                                 params=params, timeout=REQUEST_TIMEOUT)
            r.raise_for_status()
            data = r.json()
            self._parse_quota(data)
            jeu = data.get("response", {}).get("jeu")
            if self.verbose and jeu:
                found_name = jeu.get("noms", [{}])[0].get("text", "?") if jeu.get("noms") else "?"
                print(f"      [verbose] matched: '{found_name}'", file=sys.stderr)
            return jeu
        except requests.HTTPError as e:
            code = e.response.status_code if e.response is not None else 0
            if code == 404:
                if self.verbose:
                    print(f"      [verbose] 404 not found", file=sys.stderr)
                return None  # game not in DB, not an error
            if code == 403:
                # Show the actual ScreenScraper error message for diagnosis
                body = ""
                try:
                    body = e.response.text[:300]
                except Exception:
                    pass
                print(
                    f"\n    [!] 403 Forbidden for '{rom_name}'.\n"
                    f"        → Server response: {body}",
                    file=sys.stderr,
                )
                return None
            if code == 429:
                print(f"\n    [!] Rate limit — try increasing --delay.", file=sys.stderr)
                return None
            if code == 431:
                self._parse_quota_from_error(e.response)
                self.quota_exceeded = True
                qs = self.quota_str()
                print(
                    f"\n    [!] 431 Quota giornaliera esaurita per '{rom_name}'."
                    + (f"\n        → {qs}" if qs else "")
                    + "\n    [!] Nessun'altra chiamata API verrà effettuata per oggi.",
                    file=sys.stderr,
                )
                return None
            safe = e.response.url.split("?")[0] if e.response is not None else ""
            print(f"\n    [!] HTTP {code} for '{rom_name}' ({safe})", file=sys.stderr)
            return None
        except (requests.RequestException, json.JSONDecodeError) as e:
            print(f"\n    [!] API error for '{rom_name}': {type(e).__name__}: {e}",
                  file=sys.stderr)
            return None

    # Map Content-Type → file extension for media downloads
    _CONTENT_TYPE_EXT = {
        "application/pdf":  ".pdf",
        "image/jpeg":       ".jpg",
        "image/jpg":        ".jpg",
        "image/png":        ".png",
        "image/gif":        ".gif",
        "image/webp":       ".webp",
        "video/mp4":        ".mp4",
        "video/webm":       ".webm",
    }

    def download_file(self, url, dest_path):
        """Download url to dest_path. Returns True on success."""
        try:
            r = self.session.get(url, timeout=REQUEST_TIMEOUT, stream=True)
            r.raise_for_status()
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            with open(dest_path, "wb") as f:
                for chunk in r.iter_content(65536):
                    f.write(chunk)
            return True
        except requests.RequestException as e:
            print(f"\n    [!] Download failed: {e}", file=sys.stderr)
            return False

    def download_file_detect_ext(self, url, stem_path):
        """
        Download url to stem_path.<detected_ext>.
        Extension is determined from the Content-Type response header.
        Returns the actual Path used on success, or None on failure.
        """
        try:
            r = self.session.get(url, timeout=REQUEST_TIMEOUT, stream=True)
            r.raise_for_status()
            ct = r.headers.get("Content-Type", "").split(";")[0].strip().lower()
            ext = self._CONTENT_TYPE_EXT.get(ct)
            if not ext:
                # Last-resort: try URL path suffix, but ignore .php
                url_suffix = Path(urlparse(url).path).suffix.lower()
                ext = url_suffix if url_suffix and url_suffix != ".php" else ".pdf"
            dest_path = Path(str(stem_path) + ext)
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            with open(dest_path, "wb") as f:
                for chunk in r.iter_content(65536):
                    f.write(chunk)
            return dest_path
        except requests.RequestException as e:
            print(f"\n    [!] Download failed: {e}", file=sys.stderr)
            return None

    # -- Metadata extractors -------------------------------------------------

    def display_name(self, jeu, rom_region=None):
        preferred = rom_region or self.region
        return pick_region(jeu.get("noms", []), "region", preferred, fallback=self.region)

    def description(self, jeu):
        return pick_region(jeu.get("synopsis", []), "langue", self.lang, fallback="en")

    def release_date(self, jeu):
        return pick_region(jeu.get("dates", []), "region", self.region)

    def genre(self, jeu):
        genres = jeu.get("genres", [])
        if isinstance(genres, dict):
            genres = [genres]
        if not genres:
            return None
        return pick_region(genres[0].get("noms", []), "langue", self.lang, fallback="en")

    def developer(self, jeu):
        devs = jeu.get("developpeur", {})
        return devs.get("text") if devs else None

    def publisher(self, jeu):
        pub = jeu.get("editeur", {})
        return pub.get("text") if pub else None

    def players(self, jeu):
        val = jeu.get("joueurs")
        if isinstance(val, dict):
            val = val.get("text")
        return val or None

    def rating(self, jeu):
        """Return rating as a 0.0–1.0 string (EmulationStation format); source is /20."""
        note = jeu.get("note")
        if isinstance(note, dict):
            note = note.get("text")
        if note is None:
            return None
        try:
            return f"{float(note) / 20:.2f}"
        except (ValueError, TypeError):
            return None

    def all_genres(self, jeu):
        """Return all genres as a comma-separated string."""
        genres = jeu.get("genres", [])
        if isinstance(genres, dict):
            genres = [genres]
        names = []
        for g in genres:
            name = pick_region(g.get("noms", []), "langue", self.lang, fallback="en")
            if name and name not in names:
                names.append(name)
        return ", ".join(names) if names else None

    def media_url(self, jeu, media_type):
        """Return the best URL for a given media type (boxart, video, etc.)."""
        medias     = jeu.get("medias", [])
        candidates = [m for m in medias if m.get("type") == media_type]
        if not candidates:
            return None
        for reg in (self.region, "wor", "us", "eu", "jp", ""):
            for m in candidates:
                if m.get("region", "").lower() == reg.lower():
                    return m.get("url")
        return candidates[0].get("url")

    def authenticated_url(self, url):
        """Re-inject authentication parameters into a cached (stripped) URL."""
        if not url:
            return url
        parsed = urlparse(url)
        params = parse_qs(parsed.query, keep_blank_values=True)
        params.update({
            "devid":       [self.devid],
            "devpassword": [self.devpassword],
            "softname":    [SOFT_NAME],
            "ssid":        [self.user],
            "sspassword":  [self.password],
        })
        return urlunparse(parsed._replace(query=urlencode(
            {k: v[0] for k, v in params.items()}
        )))


# ---------------------------------------------------------------------------
# Scraper orchestrator
# ---------------------------------------------------------------------------
# Device profiles: map canonical media folder names to actual on-disk names.
# ---------------------------------------------------------------------------

FOLDER_PROFILES = {
    "gsg": {
        "boxart":      "boxart",
        "videos":      "videos",
        "bezels":      "bezels",
        "manuals":     "manuals",
        "marquees":    "marquees",
        "3dboxes":     "3dboxes",
        "screenshots": "screenshots",
    },
    "gsp": {
        "boxart":      "Named_Boxarts",
        "videos":      "videos",
        "bezels":      "bezels",
        "manuals":     "manuals",
        "marquees":    "Named_Titles",
        "3dboxes":     "3dboxes",
        "screenshots": "Named_Snaps",
    },
}

# ---------------------------------------------------------------------------

class Scraper:
    def __init__(self, games_dir, client,
                 do_boxart=True, do_videos=True, do_gamelist=True,
                 do_bezels=False, do_manuals=False, do_marquees=False, do_3dboxes=False,
                 do_screenshots=False,
                 overwrite=False, system_filter=None, folder_overrides=None,
                 ext_override=None, stop_event=None, verbose=False,
                 sftp_context=None, sftp_remote_base=None,
                 do_notfound_cache=False,
                 overlay_base_path="/mnt/sdcard/Games",
                 profile="gsg",
                 ra_user="", ra_key=""):
        self.games_dir      = games_dir
        self.client         = client
        self.do_boxart      = do_boxart
        self.do_videos      = do_videos
        self.do_gamelist    = do_gamelist
        self.do_bezels      = do_bezels
        self.do_manuals     = do_manuals
        self.do_marquees    = do_marquees
        self.do_3dboxes     = do_3dboxes
        self.do_screenshots = do_screenshots
        self.overwrite      = overwrite
        self.fm             = FOLDER_PROFILES.get(profile, FOLDER_PROFILES["gsg"])
        # folder_overrides: {lowercase_folder_name: system_id} — bypasses name auto-detect
        self.folder_overrides = {k.lower().strip(): v
                                 for k, v in (folder_overrides or {}).items() if v}
        self.system_filter = system_filter.lower().strip() if system_filter else None
        # ext_override: user-selected set of extensions (no leading dot) — overrides SYSTEM_EXTENSIONS
        self.ext_override  = set(ext_override) if ext_override else None
        # stop_event: threading.Event set by the GUI to request a clean stop
        self.stop_event    = stop_event
        self.verbose       = verbose
        self.client.verbose = verbose
        # SFTP: optional remote access via SSH
        self._sftp         = sftp_context        # SFTPContext | None
        self._sftp_base    = (sftp_remote_base or "").rstrip("/")
        self._sftp_sizes   = {}  # {local_stub_path: remote_file_size}
        self.do_notfound_cache = do_notfound_cache
        self.overlay_base_path = overlay_base_path.rstrip("/")
        self.ra_user   = ra_user.strip()
        self.ra_key    = ra_key.strip()
        self._ra_token = None   # obtained on first use via login
        self._ra_cache = {}     # md5 → bool, avoids duplicate RA API calls within a run
        self._ra_game_cache = {}  # game_id → bool, caches NumAchievements check

    def _write_ra_game_cfg(self, sys_dir, stem):
        """Create RetroArch game override cfg that enables the bezel overlay for this game.
        Output: <sys_dir>/bezels/copy inside retroarch/config/_<system_name>/<stem>.cfg
        """
        out_dir = sys_dir / "bezels" / "copy inside retroarch" / "config" / f"_{sys_dir.name}"
        out_dir.mkdir(parents=True, exist_ok=True)
        cfg_path = out_dir / f"{stem}.cfg"
        if self.overwrite or not cfg_path.exists():
            overlay_cfg = f"{self.overlay_base_path}/{sys_dir.name}/bezels/{stem}.cfg"
            cfg_path.write_text(
                f'input_overlay = "{overlay_cfg}"\n'
                f'input_overlay_auto_scale = "true"\n'
            )

    def _ra_login(self):
        """Login to RetroAchievements and cache the session token. Returns token or None."""
        if self._ra_token is not None:
            return self._ra_token if self._ra_token else None
        try:
            r = self.client.session.post(
                "https://retroachievements.org/dorequest.php",
                params={"r": "login2", "u": self.ra_user, "p": self.ra_key},
                timeout=10,
            )
            if self.verbose:
                print(f"      [verbose] RA login HTTP {r.status_code}: {r.text[:120]}", file=sys.stderr)
            if r.status_code == 200:
                data = r.json()
                if data.get("Success"):
                    self._ra_token = data.get("Token")
                    return self._ra_token
                else:
                    print(f"  [RA] Login error: {data.get('Error', 'unknown')}")
            else:
                print(f"  [RA] Login HTTP {r.status_code}")
        except Exception as e:
            print(f"  [RA] Login exception: {e}")
        self._ra_token = False  # mark as failed so we don't retry every ROM
        return None

    def _ra_game_has_achievements(self, game_id):
        """Return True if game_id has at least one achievement on RA (via r=patch)."""
        if game_id in self._ra_game_cache:
            return self._ra_game_cache[game_id]
        token = self._ra_login()
        if not token:
            self._ra_game_cache[game_id] = False
            return False
        try:
            r2 = self.client.session.get(
                "https://retroachievements.org/dorequest.php",
                params={"r": "patch", "u": self.ra_user, "t": token, "g": game_id},
                timeout=10,
            )
            if r2.status_code == 200:
                achievements = r2.json().get("PatchData", {}).get("Achievements", [])
                result = len(achievements) > 0
                self._ra_game_cache[game_id] = result
                return result
        except Exception as e:
            print(f"      [RA] patch lookup error: {e}")
        self._ra_game_cache[game_id] = False
        return False

    def _query_ra_cheevos(self, md5, ra_console_id=None):
        """Return True/False/None for RetroAchievements cheevos presence.

        Return values:
          True  — RA recognises the ROM and it has achievements.
          False — RA recognises the ROM (GameID > 0) but it has 0 achievements.
          None  — RA does not recognise this ROM hash (GameID=0), credentials
                  missing/failed, or a network error occurred.  The caller
                  falls back to ScreenScraper's retroachievement field.

        Returning None for GameID=0 is intentional: an unknown hash just means
        RA does not have a matching entry for this ROM version — it does NOT
        mean the game has no achievements.  ScreenScraper may still know.

        ra_console_id: optional RA console ID (see _SS_TO_RA_CONSOLE_ID).
          When provided, the gameid query is first tried without the console ID
          (global search), and if that returns 0 it is retried with c=CONSOLE_ID.
          This is needed for Arcade systems (CPS1/2/3, Neo Geo) whose hashes are
          stored under RA's Arcade console (27) and may not surface in the global
          hash lookup.
        """
        if not self.ra_user or not self.ra_key or not md5:
            return None  # not configured — caller keeps ScreenScraper value
        md5u = md5.upper()
        if md5u in self._ra_cache:
            return self._ra_cache[md5u]
        token = self._ra_login()
        if not token:
            return None

        # We try up to two queries:
        #   pass 1 — global search (no console ID)
        #   pass 2 — console-specific search (only when ra_console_id given and pass 1 missed)
        queries = [{"r": "gameid", "m": md5u, "u": self.ra_user, "t": token}]
        if ra_console_id is not None:
            queries.append({"r": "gameid", "m": md5u, "u": self.ra_user, "t": token,
                            "c": ra_console_id})

        for i, params in enumerate(queries):
            try:
                r = self.client.session.get(
                    "https://retroachievements.org/dorequest.php",
                    params=params,
                    timeout=10,
                )
                if r.status_code == 200:
                    data = r.json()
                    game_id = int(data.get("GameID", 0))
                    if game_id <= 0:
                        if i == 0 and ra_console_id is not None:
                            if self.verbose:
                                print(f"      [verbose] RA: GameID=0 (global) — retrying with console_id={ra_console_id}")
                            continue  # try console-specific query
                        # All queries exhausted — hash genuinely not in RA DB.
                        self._ra_cache[md5u] = None
                        if self.verbose:
                            print(f"      [verbose] RA: GameID=0 (hash not recognised) — falling back to ScreenScraper")
                        return None
                    # GameID found — verify it actually has achievements
                    result = self._ra_game_has_achievements(game_id)
                    self._ra_cache[md5u] = result
                    if result:
                        console_note = f" (arcade console {ra_console_id})" if i > 0 else ""
                        print(f"      [RA] cheevos found (GameID={game_id}){console_note}")
                    elif self.verbose:
                        print(f"      [verbose] RA: GameID={game_id} but 0 achievements")
                    return result
            except Exception as e:
                print(f"      [RA] hash lookup error: {e}")
                break  # don't retry on exception

        # Network/parse error or all queries missed — fall back to ScreenScraper.
        return None

    def run(self):
        print(f"AGSG CCF FE Scraper  v{SCRAPER_VERSION}")
        if self._sftp:
            self._run_sftp()
            return

        systems = sorted(p for p in self.games_dir.iterdir() if p.is_dir())
        if not systems:
            print("No system folders found in Games directory.")
            return

        # RetroAchievements login (if credentials provided)
        if self.ra_user and self.ra_key:
            print(f"RetroAchievements login ({self.ra_user})...", end=" ", flush=True)
            token = self._ra_login()
            if token:
                print("OK ✓")
            else:
                print("FAILED — cheevos detection via RA disabled for this session")

        # Fetch quota upfront so it is visible before the first ROM is processed
        print("Recover ScreenScraper quota...", end=" ", flush=True)
        if self.client.get_user_quota():
            qs = self.client.quota_str()
            print(qs if qs else "OK")
        else:
            print("not available (will be updated upon the first call)")

        # Build merged map: dynamic (all SS systems) with SYSTEM_IDS as curated override
        dynamic_map = build_screenscraper_system_ids(
            self.client.devid, self.client.devpassword)
        system_map = {**dynamic_map, **SYSTEM_IDS}

        total_scraped = 0
        for sys_dir in systems:
            if self.stop_event and self.stop_event.is_set():
                print("\n[!] Scraping interrupted by the user.")
                break
            key = sys_dir.name.lower().strip()
            if self.system_filter and key != self.system_filter:
                continue
            if key in self.folder_overrides:
                system_id = self.folder_overrides[key]
                print(f"\n[{sys_dir.name}]  (forced system → ID: {system_id})")
            else:
                system_id = system_map.get(key)
                if system_id is None:
                    print(f"\n[{sys_dir.name}] — no ScreenScraper mapping, skipping")
                    continue
                print(f"\n[{sys_dir.name}]  (ScreenScraper system ID: {system_id})")
            total_scraped += self._scrape_system(sys_dir, system_id)

        print(f"\n{'='*60}")
        print(f"Total games processed: {total_scraped}")
        qs = self.client.quota_str()
        if qs:
            print(qs)

    # ------------------------------------------------------------------
    # SFTP mode: list ROMs from remote device, write outputs back via SSH
    # ------------------------------------------------------------------

    def _run_sftp(self):
        """Entry point for SSH mode: mirrors remote structure locally, scrapes,
        then uploads all outputs back to the device."""
        staging = Path(tempfile.mkdtemp(prefix="scraper_ssh_"))
        try:
            # Fetch quota first
            print("Recover ScreenScraper quota...", end=" ", flush=True)
            if self.client.get_user_quota():
                qs = self.client.quota_str()
                print(qs if qs else "OK")
            else:
                print("not available (will be updated upon the first call)")

            dynamic_map = build_screenscraper_system_ids(
                self.client.devid, self.client.devpassword)
            system_map = {**dynamic_map, **SYSTEM_IDS}

            system_names = self._sftp.list_subdirs(self._sftp_base)
            if not system_names:
                print(f"No system folders found in remote path: {self._sftp_base}")
                return

            total_scraped = 0
            for sys_name in sorted(system_names):
                if self.stop_event and self.stop_event.is_set():
                    print("\n[!] Scraping interrupted by the user.")
                    break
                key = sys_name.lower().strip()
                if self.system_filter and key != self.system_filter:
                    continue
                if key in self.folder_overrides:
                    system_id = self.folder_overrides[key]
                    print(f"\n[{sys_name}]  (sistema forzato → ID: {system_id})")
                else:
                    system_id = system_map.get(key)
                    if system_id is None:
                        print(f"\n[{sys_name}] — no ScreenScraper mapping, skipping")
                        continue
                    print(f"\n[{sys_name}]  (ScreenScraper system ID: {system_id})")

                local_sys = staging / sys_name
                local_sys.mkdir(parents=True, exist_ok=True)
                remote_sys = self._sftp_base + "/" + sys_name

                self._sftp_sync_in(remote_sys, local_sys)
                n = self._scrape_system(local_sys, system_id)
                total_scraped += n
                if n > 0 or True:  # always sync out to push gamelist.xml
                    self._sftp_sync_out(remote_sys, local_sys)

            print(f"\n{'='*60}")
            print(f"Total games processed: {total_scraped}")
            qs = self.client.quota_str()
            if qs:
                print(qs)
        finally:
            shutil.rmtree(staging, ignore_errors=True)
            self._sftp.close()

    def _sftp_sync_in(self, remote_sys, local_sys):
        """
        Prepare the local staging dir before scraping:
          - Create 0-byte stub files for remote ROMs (so _find_roms can list them)
          - Create 0-byte sentinel files for existing media (so .exists() works)
          - Download .metadata/*.json so cached games can be re-used
        """
        MEDIA_SUBDIRS = list(self.fm.values())
        SKIP_DIRS     = set(MEDIA_SUBDIRS) | {".metadata"}

        # -- ROM stubs --
        all_remote = self._sftp.list_files_recursive(remote_sys)
        for remote_path, size, filename in all_remote:
            rel = remote_path[len(remote_sys):].lstrip("/")
            parts = rel.split("/")
            if parts[0].lower() in SKIP_DIRS:
                continue  # skip media / metadata dirs
            local_file = local_sys / rel
            local_file.parent.mkdir(parents=True, exist_ok=True)
            local_file.touch()  # 0-byte stub — just the filename matters
            self._sftp_sizes[local_file] = size

        # -- Media sentinel files --
        for sub in MEDIA_SUBDIRS:
            remote_sub = remote_sys + "/" + sub
            filenames  = self._sftp.list_files_in_dir(remote_sub)
            if not filenames:
                continue
            local_sub = local_sys / sub
            local_sub.mkdir(exist_ok=True)
            for fn in filenames:
                (local_sub / fn).touch()  # sentinel: marks file as already on device

        # -- Metadata JSON (download so cache is usable) --
        remote_meta = remote_sys + "/.metadata"
        meta_files  = self._sftp.list_files_in_dir(remote_meta)
        if meta_files:
            local_meta = local_sys / ".metadata"
            local_meta.mkdir(exist_ok=True)
            for fn in meta_files:
                if fn.endswith(".json"):
                    try:
                        self._sftp.get(remote_meta + "/" + fn, local_meta / fn)
                    except Exception:
                        pass

    def _sftp_sync_out(self, remote_sys, local_sys):
        """
        Upload scraper outputs from local staging to the remote device.
        Skips 0-byte files (they are sentinels for pre-existing remote files).
        """
        UPLOAD_SUBDIRS = list(self.fm.values()) + [".metadata"]
        items_to_upload = []

        # gamelist.xml
        gl = local_sys / "gamelist.xml"
        if gl.exists() and gl.stat().st_size > 0:
            items_to_upload.append(gl)

        # Media and metadata sub-dirs (skip 0-byte sentinels)
        for sub in UPLOAD_SUBDIRS:
            subdir = local_sys / sub
            if not subdir.is_dir():
                continue
            for f in subdir.iterdir():
                if f.is_file() and f.stat().st_size > 0:
                    items_to_upload.append(f)

        for local_file in items_to_upload:
            rel = local_file.relative_to(local_sys).as_posix()
            remote_dest = remote_sys + "/" + rel
            try:
                self._sftp.put(str(local_file), remote_dest)
                if self.verbose:
                    print(f"  [SSH] uploaded {rel}", file=sys.stderr)
            except Exception as e:
                print(f"  [!] SSH upload failed for {rel}: {e}", file=sys.stderr)

    # ------------------------------------------------------------------
    # Not-found cache helpers
    # ------------------------------------------------------------------

    def _notfound_cache_path(self, sys_dir):
        return sys_dir / ".metadata" / ".notfound.json"

    def _load_notfound_cache(self, sys_dir):
        """Return a set of ROM filenames previously confirmed as not found."""
        p = self._notfound_cache_path(sys_dir)
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
            return set(data) if isinstance(data, list) else set()
        except (OSError, json.JSONDecodeError):
            return set()

    def _save_notfound_cache(self, sys_dir, cache_set):
        """Persist the set of not-found ROM filenames to disk."""
        p = self._notfound_cache_path(sys_dir)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(sorted(cache_set), f, ensure_ascii=False, indent=2)

    def _scrape_system(self, sys_dir, system_id):
        roms = self._find_roms(sys_dir, system_id)
        if not roms:
            print("  No ROMs found.")
            return 0

        # Load not-found cache (empty set if feature disabled or no cache yet)
        notfound_cache = self._load_notfound_cache(sys_dir) if self.do_notfound_cache else set()
        notfound_cache_dirty = False  # tracks whether the cache was modified

        entries  = []
        scraped  = 0
        cached   = 0
        notfound = 0
        skipped_notfound = 0

        for rom_path in roms:
            if self.stop_event and self.stop_event.is_set():
                print("\n  [!] Scraping interrupted by the user.")
                break
            stem    = rom_path.stem

            # All media goes into profile-mapped subfolders of sys_dir
            fm = self.fm
            boxart_dest  = sys_dir / fm["boxart"]      / f"{stem}.png"
            video_dest   = sys_dir / fm["videos"]      / f"{stem}.mp4"
            bezel_dest   = sys_dir / fm["bezels"]      / f"{stem}.png"
            marquee_dest = sys_dir / fm["marquees"]    / f"{stem}.png"
            box3d_dest      = sys_dir / fm["3dboxes"]     / f"{stem}.png"
            screenshot_dest = sys_dir / fm["screenshots"] / f"{stem}.png"
            manual_dir      = sys_dir / fm["manuals"]
            rel_rom      = rom_path.relative_to(sys_dir)
            rel_rom_str  = rel_rom.as_posix()  # always forward slashes for gamelist.xml

            # Metadata cache: stores name/desc/genre/etc from previous API calls
            meta_cache_path = sys_dir / ".metadata" / f"{stem}.json"
            meta_cached     = meta_cache_path.exists()

            # Load cached metadata early (fallback values + skip-API optimisation)
            _cached_meta = {}
            _cached_media_urls = {}
            if meta_cached:
                try:
                    with open(meta_cache_path, "r", encoding="utf-8") as _f:
                        _cached_meta = json.load(_f)
                        _cached_media_urls = _cached_meta.get("media_urls", {})
                except (OSError, json.JSONDecodeError):
                    pass

            # Already fully cached: skip API call
            _manual_exists  = bool(list(manual_dir.glob(f"{stem}.*")))
            _bezel_cached      = not self.do_bezels      or bezel_dest.exists()
            _manual_cached     = not self.do_manuals     or _manual_exists
            _marquee_cached    = not self.do_marquees    or marquee_dest.exists()
            _3dbox_cached      = not self.do_3dboxes     or box3d_dest.exists()
            _screenshot_cached = not self.do_screenshots or screenshot_dest.exists()
            all_media_cached = (boxart_dest.exists() if self.do_boxart else True) and \
                               (video_dest.exists()  if self.do_videos  else True) and \
                               _bezel_cached and _manual_cached and _marquee_cached and \
                               _3dbox_cached and _screenshot_cached
            # Metadata is "complete" only when:
            #   - cheevos field is present in cache  (predates cheevos → re-query)
            #   - AND if RA credentials are provided, the cache was built with an
            #     actual RA query (cheevos_ra_checked=true).  Without this flag the
            #     old (buggy) scraper had stored cheevos=false from a failed RA lookup
            #     that was really "hash unknown" — we must re-query to get the right value.
            _ra_creds = bool(self.ra_user and self.ra_key)
            _meta_complete = (
                meta_cached and
                ("cheevos" in _cached_meta) and
                (not _ra_creds or _cached_meta.get("cheevos_ra_checked", False))
            )
            all_cached = all_media_cached and (not self.do_gamelist or _meta_complete)
            if not self.overwrite and all_cached:
                print(f"  {rom_path.name}  [cached]")
                if self.do_bezels and bezel_dest.exists():
                    cfg_dest = bezel_dest.with_suffix(".cfg")
                    if not cfg_dest.exists():
                        cfg_dest.write_text(
                            f"overlays = 1\n\n"
                            f'overlay0_overlay = "{stem}.png"\n'
                            f"overlay0_full_screen = true\n"
                            f"overlay0_descs = 0\n"
                        )
                    self._write_ra_game_cfg(sys_dir, stem)
                if self.do_gamelist:
                    entries.append(self._load_meta_entry(rom_path, sys_dir, meta_cache_path))
                else:
                    entries.append(self._stub_entry(rom_path, sys_dir))
                cached  += 1
                continue

            # If metadata and all needed media URLs are already cached we can skip
            # the jeuInfos API call entirely, saving 1 scrape per game from quota.
            _can_skip_api = (
                not self.overwrite and meta_cached and bool(_cached_media_urls) and
                (not self.do_boxart      or boxart_dest.exists()      or "boxart"      in _cached_media_urls) and
                (not self.do_videos      or video_dest.exists()       or "video"       in _cached_media_urls) and
                (not self.do_bezels      or bezel_dest.exists()       or "bezel"       in _cached_media_urls) and
                (not self.do_manuals     or _manual_exists             or "manual"      in _cached_media_urls) and
                (not self.do_marquees    or marquee_dest.exists()     or "marquee"     in _cached_media_urls) and
                (not self.do_3dboxes     or box3d_dest.exists()       or "3dbox"       in _cached_media_urls) and
                (not self.do_screenshots or screenshot_dest.exists()  or "screenshot"  in _cached_media_urls)
            )

            # Not-found cache: skip API call for ROMs previously not found
            # (only when do_notfound_cache=True and not overwrite mode)
            if self.do_notfound_cache and not self.overwrite and rom_path.name in notfound_cache:
                print(f"  {rom_path.name}  [skipped - previously not found]")
                if meta_cache_path.exists():
                    entries.append(self._load_meta_entry(rom_path, sys_dir, meta_cache_path))
                else:
                    entries.append(self._stub_entry(rom_path, sys_dir))
                skipped_notfound += 1
                continue

            print(f"  {rom_path.name}", end="", flush=True)

            jeu = None
            if not _can_skip_api:
                _sftp_size = self._sftp_sizes.get(rom_path)
                if _sftp_size is not None:
                    jeu = self.client.get_game_info(system_id, rom_path.name,
                                                    file_size=_sftp_size)
                else:
                    jeu = self.client.get_game_info(system_id, rom_path.name, rom_path)
                if self.client.quota_exceeded:
                    print(f"\n  [!] Quota exhausted — scraping interrupted. The remaining ROMs will be skipped.")
                    break
                if not jeu:
                    print("  [not found]")
                    if self.verbose:
                        cleaned = strip_rom_tags(rom_path.name)
                        if cleaned != rom_path.name:
                            print(f"      [verbose] also tried cleaned name: '{cleaned}'",
                                  file=sys.stderr)
                    # Add to not-found cache
                    if self.do_notfound_cache:
                        notfound_cache.add(rom_path.name)
                        notfound_cache_dirty = True
                    # Preserve previously cached metadata if available (avoids losing
                    # descriptions when a game can't be reached due to quota/rate limits)
                    if meta_cache_path.exists():
                        entries.append(self._load_meta_entry(rom_path, sys_dir, meta_cache_path))
                    else:
                        entries.append(self._stub_entry(rom_path, sys_dir))
                    notfound += 1
                    continue

            _rom_region = _detect_region_from_filename(rom_path.stem)
            ss_id     = str(jeu.get("id", "")) if jeu else _cached_meta.get("ss_id", "")
            # cheevos: RA API when credentials provided and hash recognised (True/False);
            # returns None when hash unknown → falls back to ScreenScraper field, then cache.
            _ss_cheevos = (jeu.get("rom", {}).get("retroachievement", "0") == "1") if jeu else None
            _ra_result = None
            if self.do_gamelist and self.ra_user and self.ra_key and rom_path and rom_path.exists():
                try:
                    _rom_md5 = _ra_rom_md5(rom_path, system_id=system_id)
                    if not _rom_md5:
                        raise ValueError("hash failed")
                    print(f"      [RA] querying MD5={_rom_md5.upper()}  ({rom_path.name})")
                    _ra_console_id = _SS_TO_RA_CONSOLE_ID.get(system_id)
                    _ra_result = self._query_ra_cheevos(_rom_md5, ra_console_id=_ra_console_id)
                except Exception as e:
                    print(f"      [RA] hash error: {e}")
            if _ra_result is not None:
                cheevos = _ra_result
            elif _ss_cheevos is not None:
                cheevos = _ss_cheevos
            else:
                cheevos = _cached_meta.get("cheevos", False)
            name      = (self.client.display_name(jeu, _rom_region) if jeu else None) or _cached_meta.get("name") or stem
            desc      = (self.client.description(jeu)  if jeu else None) or _cached_meta.get("desc", "")
            date      = (self.client.release_date(jeu) if jeu else None) or _cached_meta.get("releasedate", "")
            genre     = (self.client.all_genres(jeu)   if jeu else None) or _cached_meta.get("genre", "")
            developer = (self.client.developer(jeu)    if jeu else None) or _cached_meta.get("developer", "")
            publisher = (self.client.publisher(jeu)    if jeu else None) or _cached_meta.get("publisher", "")
            players   = (self.client.players(jeu)      if jeu else None) or _cached_meta.get("players", "")
            rating    = (self.client.rating(jeu)       if jeu else None) or _cached_meta.get("rating", "")

            if self.verbose and not desc and jeu:
                synopsis_raw = jeu.get("synopsis", [])
                print(f"      [verbose] desc: not found — synopsis in API response: {synopsis_raw!r}",
                      file=sys.stderr)

            status    = []

            # Collect all media URLs from fresh jeu response, merged with existing cache
            _new_media_urls = dict(_cached_media_urls)
            if jeu:
                for _cache_key, _media_types in [
                    ("boxart",      ["box-2D"]),
                    ("video",       ["video-normalized", "video"]),
                    ("bezel",       ["bezel-16-9"]),
                    ("marquee",     ["wheel-hd", "wheel"]),
                    ("manual",      ["manuel"]),
                    ("3dbox",       ["box-3D"]),
                    ("screenshot",  ["ss", "sstitle"]),
                ]:
                    for _mt in _media_types:
                        _u = self.client.media_url(jeu, _mt)
                        if _u:
                            _new_media_urls[_cache_key] = _strip_auth_params(_u)
                            break

            def _media_url(cache_key, *media_types):
                """Return media URL from fresh jeu (preferred) or URL cache."""
                if jeu:
                    for mt in media_types:
                        u = self.client.media_url(jeu, mt)
                        if u:
                            return u
                cached_url = _new_media_urls.get(cache_key)
                return self.client.authenticated_url(cached_url) if cached_url else None

            # --- Boxart ---
            boxart_ok = boxart_dest.exists()  # reference existing file even if do_boxart=False
            if self.do_boxart and (self.overwrite or not boxart_dest.exists()):
                url = _media_url("boxart", "box-2D")
                if url:
                    boxart_ok = self.client.download_file(url, boxart_dest)
                    if boxart_ok:
                        status.append("boxart")
            elif self.do_boxart and boxart_dest.exists():
                status.append("boxart (cached)")

            # --- Video snap ---
            video_ok = video_dest.exists()  # reference existing file even if do_videos=False
            if self.do_videos and (self.overwrite or not video_dest.exists()):
                url = _media_url("video", "video-normalized", "video")
                if url:
                    video_ok = self.client.download_file(url, video_dest)
                    if video_ok:
                        status.append("video")
            elif self.do_videos and video_dest.exists():
                status.append("video (cached)")

            # --- Bezel (16:9) ---
            if self.do_bezels and (self.overwrite or not bezel_dest.exists()):
                url = _media_url("bezel", "bezel-16-9")
                if url:
                    if self.client.download_file(url, bezel_dest):
                        status.append("bezel")
            elif self.do_bezels and bezel_dest.exists():
                status.append("bezel (cached)")
            if self.do_bezels and bezel_dest.exists():
                cfg_dest = bezel_dest.with_suffix(".cfg")
                if self.overwrite or not cfg_dest.exists():
                    cfg_dest.write_text(
                        f"overlays = 1\n\n"
                        f'overlay0_overlay = "{stem}.png"\n'
                        f"overlay0_full_screen = true\n"
                        f"overlay0_descs = 0\n"
                    )
                self._write_ra_game_cfg(sys_dir, stem)

            # --- Manual ---
            if self.do_manuals:
                existing_manual = list(manual_dir.glob(f"{stem}.*"))
                if self.overwrite or not existing_manual:
                    url = _media_url("manual", "manuel")
                    if url:
                        manual_stem = manual_dir / stem
                        if self.client.download_file_detect_ext(url, manual_stem):
                            status.append("manual")
                else:
                    status.append("manual (cached)")

            # --- Marquee (wheel logo) ---
            if self.do_marquees and (self.overwrite or not marquee_dest.exists()):
                url = _media_url("marquee", "wheel-hd", "wheel")
                if url:
                    if self.client.download_file(url, marquee_dest):
                        status.append("marquee")
            elif self.do_marquees and marquee_dest.exists():
                status.append("marquee (cached)")

            # --- 3D Box ---
            if self.do_3dboxes and (self.overwrite or not box3d_dest.exists()):
                url = _media_url("3dbox", "box-3D")
                if url:
                    if self.client.download_file(url, box3d_dest):
                        status.append("3D box")
            elif self.do_3dboxes and box3d_dest.exists():
                status.append("3D box (cached)")

            # --- Screenshot ---
            screenshot_ok = screenshot_dest.exists()  # reference existing file even if do_screenshots=False
            if self.do_screenshots and (self.overwrite or not screenshot_dest.exists()):
                url = _media_url("screenshot", "ss", "sstitle")
                if url:
                    screenshot_ok = self.client.download_file(url, screenshot_dest)
                    if screenshot_ok:
                        status.append("screenshot")
            elif self.do_screenshots and screenshot_dest.exists():
                status.append("screenshot (cached)")

            print(f"  [{', '.join(status) if status else 'metadata only'}]")

            self._save_meta_cache(meta_cache_path, name, desc, date, genre, developer,
                                  publisher, players, rating, _new_media_urls, ss_id, cheevos,
                                  cheevos_ra_checked=_ra_creds)

            entries.append({
                "path":        f"./{rel_rom_str}",
                "name":        name,
                "ss_id":       ss_id,
                "cheevos":     "1" if cheevos else "",
                "desc":        desc,
                "releasedate": date,
                "genre":       genre,
                "developer":   developer,
                "publisher":   publisher or "",
                "players":     players   or "",
                "rating":      rating    or "",
                "image":       f"./{fm['boxart']}/{stem}.png"       if boxart_ok      else "",
                "video":       f"./{fm['videos']}/{stem}.mp4"       if video_ok       else "",
                "screenshot":  f"./{fm['screenshots']}/{stem}.png"  if screenshot_ok  else "",
            })
            scraped += 1

        if self.do_gamelist and entries:
            self._write_gamelist(sys_dir, entries)

        # Persist the not-found cache if it was modified
        if notfound_cache_dirty:
            self._save_notfound_cache(sys_dir, notfound_cache)

        _nf_parts = [f"{notfound} not found"]
        if skipped_notfound:
            _nf_parts.append(f"{skipped_notfound} skipped (not-found cache)")
        print(f"  ► {scraped} scraped  |  {cached} cached  |  {'  |  '.join(_nf_parts)}")
        qs = self.client.quota_str()
        if qs:
            print(f"  ► {qs}")
        return scraped + cached

    def _save_meta_cache(self, path, name, desc, date, genre, developer,
                         publisher="", players="", rating="", media_urls=None, ss_id="", cheevos=False,
                         cheevos_ra_checked=False):
        """Persist metadata from ScreenScraper for use in future runs.

        cheevos_ra_checked=True means the cheevos value was determined by an
        actual RetroAchievements API query in this run, not just from
        ScreenScraper's retroachievement field or a stale cache.  Future runs
        with RA credentials will trust the cached value only if this flag is set.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        data = {"name": name, "desc": desc, "releasedate": date,
                "genre": genre, "developer": developer,
                "publisher":         publisher or "",
                "players":           players   or "",
                "rating":            rating    or "",
                "ss_id":             ss_id     or "",
                "cheevos":           cheevos,
                "cheevos_ra_checked": cheevos_ra_checked}
        if media_urls:
            data["media_urls"] = {k: _strip_auth_params(v) for k, v in media_urls.items() if v}
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    def _load_meta_entry(self, rom_path, sys_dir, meta_cache_path):
        """Build a gamelist entry from cached metadata JSON + existing media."""
        stem        = rom_path.stem
        rel_rom     = rom_path.relative_to(sys_dir)
        rel_rom_str = rel_rom.as_posix()
        fm = self.fm
        boxart_ok     = (sys_dir / fm["boxart"]      / f"{stem}.png").exists()
        video_ok      = (sys_dir / fm["videos"]      / f"{stem}.mp4").exists()
        screenshot_ok = (sys_dir / fm["screenshots"] / f"{stem}.png").exists()
        try:
            with open(meta_cache_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
        except (OSError, json.JSONDecodeError):
            meta = {}
        return {
            "path":        f"./{rel_rom_str}",
            "name":        meta.get("name") or stem,
            "ss_id":       meta.get("ss_id", ""),
            "cheevos":     "1" if meta.get("cheevos") else "",
            "desc":        meta.get("desc", ""),
            "releasedate": meta.get("releasedate", ""),
            "genre":       meta.get("genre", ""),
            "developer":   meta.get("developer", ""),
            "publisher":   meta.get("publisher", ""),
            "players":     meta.get("players", ""),
            "rating":      meta.get("rating", ""),
            "image":       f"./{fm['boxart']}/{stem}.png"       if boxart_ok      else "",
            "video":       f"./{fm['videos']}/{stem}.mp4"       if video_ok       else "",
            "screenshot":  f"./{fm['screenshots']}/{stem}.png"  if screenshot_ok  else "",
        }

    def _find_roms(self, sys_dir, system_id=None):
        """Recursively find all ROM files, skipping media folders.

        When system_id is known and present in SYSTEM_EXTENSIONS, a whitelist
        of recognised ROM extensions is used (recommended — avoids wasting
        ScreenScraper quota on non-ROM files).  Falls back to a blacklist of
        obviously non-ROM extensions when no whitelist is available.
        """
        skip_dirs  = set(self.fm.values()) | {".metadata"}
        skip_names = {"gamelist.xml"}

        # Build whitelist: GUI ext_override takes highest priority, then SYSTEM_EXTENSIONS
        allowed_exts = None
        if self.ext_override is not None:
            allowed_exts = {'.' + e for e in self.ext_override}
        elif system_id is not None and system_id in SYSTEM_EXTENSIONS:
            allowed_exts = {'.' + e for e in SYSTEM_EXTENSIONS[system_id]}

        # Fallback blacklist (used only when whitelist is unavailable)
        skip_exts = {".xml", ".txt", ".cfg", ".ini", ".log", ".sh", ".py",
                     ".json", ".png", ".jpg", ".jpeg", ".gif", ".bmp",
                     ".mp4", ".avi", ".mkv", ".webm", ".org", ".nfo"}

        roms = []
        for item in sorted(sys_dir.rglob("*")):
            if any(part.lower() in skip_dirs for part in item.parts):
                continue
            if item.is_file() and item.name.lower() not in skip_names:
                if allowed_exts is not None:
                    if item.suffix.lower() in allowed_exts:
                        roms.append(item)
                else:
                    if item.suffix.lower() not in skip_exts:
                        roms.append(item)
        return roms

    def _stub_entry(self, rom_path, sys_dir):
        """Entry for a ROM with no API result (keeps existing media references)."""
        stem        = rom_path.stem
        rel_rom     = rom_path.relative_to(sys_dir)
        rel_rom_str = rel_rom.as_posix()  # always forward slashes for gamelist.xml
        fm = self.fm
        boxart_ok     = (sys_dir / fm["boxart"]      / f"{stem}.png").exists()
        video_ok      = (sys_dir / fm["videos"]      / f"{stem}.mp4").exists()
        screenshot_ok = (sys_dir / fm["screenshots"] / f"{stem}.png").exists()
        return {
            "path":        f"./{rel_rom_str}",
            "name":        stem,
            "ss_id":       "",
            "desc":        "",
            "releasedate": "",
            "genre":       "",
            "developer":   "",
            "publisher":   "",
            "players":     "",
            "rating":      "",
            "image":       f"./{fm['boxart']}/{stem}.png"       if boxart_ok      else "",
            "video":       f"./{fm['videos']}/{stem}.mp4"       if video_ok       else "",
            "screenshot":  f"./{fm['screenshots']}/{stem}.png"  if screenshot_ok  else "",
        }

    # XML 1.0 allows only: #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
    _INVALID_XML_CHARS_RE = re.compile(
        r'[^\x09\x0A\x0D\x20-\uD7FF\uE000-\uFFFD\U00010000-\U0010FFFF]'
    )

    @staticmethod
    def _sanitize_xml(text):
        """Remove characters that are illegal in XML 1.0."""
        if not text:
            return text
        if not isinstance(text, str):
            text = str(text)
        return Scraper._INVALID_XML_CHARS_RE.sub('', text)

    def _write_gamelist(self, sys_dir, entries):
        root = ET.Element("gameList")
        TAGS = ("path", "name", "cheevos", "desc", "releasedate", "genre", "developer",
                "publisher", "players", "rating", "image", "video", "screenshot")
        for e in entries:
            attrs = {"id": e["ss_id"], "source": "ScreenScraper.fr"} if e.get("ss_id") else {}
            game = ET.SubElement(root, "game", attrs)
            for tag in TAGS:
                val = e.get(tag, "")
                if val:
                    ET.SubElement(game, tag).text = self._sanitize_xml(val)

        raw    = ET.tostring(root, encoding="unicode")
        pretty = xml.dom.minidom.parseString(raw).toprettyxml(indent="  ")
        lines  = pretty.split("\n")
        output = '<?xml version="1.0"?>\n' + "\n".join(lines[1:])

        out_path = sys_dir / "gamelist.xml"
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(output)
        print(f"  Wrote {out_path.name}  ({len(entries)} entries)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        prog="scraper.py",
        description="AGSG CCF FE Scraper — powered by ScreenScraper.fr",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 scraper.py --games-dir /media/user/SDCARD/Games --user Kefren68
  python3 scraper.py --games-dir /media/user/SDCARD/Games --user Kefren68 --system SNES
  python3 scraper.py --games-dir /media/user/SDCARD/Games --user Kefren68 --no-videos --overwrite

Registration: https://www.screenscraper.fr/membreinscription.php
Note: use your USERNAME, not your email address.
""",
    )
    parser.add_argument("--games-dir", required=True, type=Path, metavar="PATH",
                        help="Path to the Games directory on the SD card")
    parser.add_argument("--user", required=True,
                        help="ScreenScraper username (not email)")
    parser.add_argument("--password", default="",
                        help="ScreenScraper password (prompted if omitted)")
    parser.add_argument("--devid", default=None,
                        help="ScreenScraper developer ID (default: built-in)")
    parser.add_argument("--devpassword", default=None,
                        help="ScreenScraper developer password (default: built-in)")
    parser.add_argument("--system", default=None, metavar="NAME",
                        help="Scrape only this system folder (e.g. 'SNES'). Case-insensitive.")
    parser.add_argument("--region", default="eu", choices=["eu", "us", "jp", "wor"],
                        help="Preferred region for names/boxart/dates (default: eu)")
    parser.add_argument("--lang", default="en",
                        choices=["en", "fr", "de", "es", "it", "pt", "nl", "ja", "ko", "ru", "zh"],
                        help="Language for game info/descriptions (default: en). Falls back to English if not available.")
    parser.add_argument("--no-boxart",   action="store_true", help="Skip boxart download")
    parser.add_argument("--no-videos",   action="store_true", help="Skip video snap download")
    parser.add_argument("--no-gamelist", action="store_true", help="Skip gamelist.xml generation")
    parser.add_argument("--bezels",      action="store_true", help="Download 16:9 bezels (saved in bezels/)")
    parser.add_argument("--manuals",     action="store_true", help="Download game manuals PDF/image (saved in manuals/)")
    parser.add_argument("--marquees",    action="store_true", help="Download marquee/wheel logos (saved in marquees/)")
    parser.add_argument("--3dboxes",     action="store_true", dest="boxes3d",    help="Download 3D box art (saved in 3dboxes/)")
    parser.add_argument("--screenshots", action="store_true", dest="screenshots", help="Download in-game screenshots (saved in screenshots/)")
    parser.add_argument("--overwrite",   action="store_true",
                        help="Re-download media even if files already exist")
    parser.add_argument("--notfound-cache", action="store_true", dest="notfound_cache",
                        help="Remember ROMs not found on ScreenScraper and skip them on future runs (saves KO quota)")
    parser.add_argument("--profile", choices=list(FOLDER_PROFILES.keys()), default="gsg",
                        help="Device profile that controls media folder names (default: gsg)")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Show API calls, MD5 hashes and match details for every ROM")
    parser.add_argument("--delay", type=float, default=DEFAULT_DELAY, metavar="SECONDS",
                        help=f"Delay between API requests in seconds (default: {DEFAULT_DELAY})")

    args = parser.parse_args()

    if not args.games_dir.is_dir():
        print(f"Error: '{args.games_dir}' is not a directory.", file=sys.stderr)
        sys.exit(1)

    password = args.password or getpass("ScreenScraper password: ")

    client = ScreenScraperClient(
        user=args.user,
        password=password,
        devid=args.devid,
        devpassword=args.devpassword,
        region=args.region,
        lang=args.lang,
        delay=args.delay,
        verbose=args.verbose,
    )

    scraper = Scraper(
        games_dir=args.games_dir,
        client=client,
        do_boxart=not args.no_boxart,
        do_videos=not args.no_videos,
        do_gamelist=not args.no_gamelist,
        do_bezels=args.bezels,
        do_manuals=args.manuals,
        do_marquees=args.marquees,
        do_3dboxes=args.boxes3d,
        do_screenshots=args.screenshots,
        overwrite=args.overwrite,
        system_filter=args.system,
        verbose=args.verbose,
        do_notfound_cache=args.notfound_cache,
        profile=args.profile,
    )

    print("AGSG CCF FE Scraper — powered by ScreenScraper.fr")
    print(f"  Games dir : {args.games_dir}")
    print(f"  User      : {args.user}  |  Region: {args.region}  |  Lang: {args.lang}")
    print(f"  Boxart: {'yes' if not args.no_boxart else 'no'}"
          f"  |  Videos: {'yes' if not args.no_videos else 'no'}"
          f"  |  Bezels: {'yes' if args.bezels else 'no'}"
          f"  |  Manuals: {'yes' if args.manuals else 'no'}"
          f"  |  Marquees: {'yes' if args.marquees else 'no'}"
          f"  |  3D boxes: {'yes' if args.boxes3d else 'no'}"
          f"  |  Screenshots: {'yes' if args.screenshots else 'no'}"
          f"  |  Gamelist: {'yes' if not args.no_gamelist else 'no'}"
          f"  |  Not-found cache: {'yes' if args.notfound_cache else 'no'}")
    print()

    try:
        scraper.run()
    except KeyboardInterrupt:
        print("\n\nInterrupted by user.")
        sys.exit(0)

    print("\nAll done.")


if __name__ == "__main__":
    main()
